version: '3.8'

services:
  postgres:
    image: postgres:14-alpine  # Change the version here (e.g., postgres:13.6)
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contabil-dividas
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
